<ips:template parameters="$tab"/>
{{if \IPS\Member::loggedIn()->canBecomeVerified()}}
    <li>
        <a href='{url="app=core&module=system&controller=settings&area=auth" seoTemplate="settings_auth"}' id='setting_auth' class='ipsType_normal ipsSideMenu_item {{if $tab === 'auth'}}ipsSideMenu_itemActive{{endif}}' title="Vex Auth" role="tab" aria-selected="{{if $tab === 'auth'}}true{{else}}false{{endif}}">
        <i class='fa fa-vimeo'></i> Vex Auth
        </a>
    </li>
{{endif}}