<ips:template parameters="$form, $getContent"/>
<section class='ipsBox'>
<!-- <h2 class="ipsType_sectionHead">reee test</h2> -->
<div> <textarea readonly id='console1' class='.ipsPad, .ipsApp ul.ipsPad, .ipsApp ol.ipsPad' style='margin-top: 0px; margin-bottom: 0px; height: 500px; cursor: auto;' data-controller='vexationmanager.admin.vexationmanager.console'>{$getContent}</textarea></div>
{$form|raw}
</section>

