<?php

$lang = array(
	'__app_vexationmanager'	=> "Vexation Manager",
	'menutab__vexationmanager' => "Vexation Manager",
	'title__vexationmanager_vexationmanager_usermanager' => "Vexation Manager",
	'menu__vexationmanager_vexationmanager' => "Vexation Settings",
	'menu__vexationmanager_vexationmanager_settings' => "Settings",
	'menu__vexationmanager_vexationmanager_usermanager' => "User Manager",
	'vexationmanager_permitted_groups' => "Groups to use Vex Auth",
	'menu__vexationmanager_vexationserver' => "Vexation's Users Settings",
	'menu__vexationmanager_vexationserver_usermanager' => "User Manager",
	'menutab__vexationmanager_icon' => "vimeo",
	'r__usermanager_manage' => "Can manage Vexation server users",
	'can_access_server_info' => "Can Access Vexation User Panel",
	'module__vexationmanager_vexationmanager' => "Vexation Manager",
	'vex_user_panel' => "User Panel",
	'can_access_vex_userpanel' => "Can use forums usermanager?",
	'vexation_usermanager_photo' => "Profile Picture",
	'vexation_usermanager_member_id' => "Forums Username",
	'vexation_usermanager_uuid' => "Minecraft UUID",
	'vexation_usermanager_username' => "Minecraft Username",
	'vexation_usermanager_primary_group' => "Minecraft Role",
	'console_content' => "Send Command",
	'vexation_sub_packages' => "Vexation Packages",
	'user_settings' => "Edit User",
	'uuid' => "Minecraft UUID",
	'log_type_title_uuid_removed' => "Removed UUID",
	'log_type_title_uuid_add' => "Added UUID",
	'log_type_title_uuid_change' => "Changed UUID To",
	'log_type_title_uuid_used_onPurchase' => "Purchase History",
	'no_uuid_store' => "You need to link your Minecraft Account using our Vex Auth. <br> <a href='/settings/vexauth/?area=auth'>Click here to get started</a>",
);
